{
 "title": "API Gateway Monitoring",
 "description": "This dashboard monitors API Gateway metrics: total routes, request rate, average response time, and 5xx errors.\n",
 "tags": [
  "api-gateway",
  "microservices",
  "grafana ",
  "promethus",
  "monitoring "
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "auto",
 "panels": [
  {
   "title": "Gateway – Avg Response Time (sec)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(http_server_requests_seconds_sum{application=\"API-GATEWAY\"}[1m])\r\n/\r\nrate(http_server_requests_seconds_count{application=\"API-GATEWAY\"}[1m])\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Gateway – Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"API-GATEWAY\"}[1m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Gateway – Total Routes", "type": "library-panel-ref", "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 } },
  {
   "title": "Gateway – 5xx Error Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum(rate(http_server_requests_seconds_count{application=\"API-GATEWAY\"}[5m]))\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}